"""replace variable value with variable_type

Revision ID: eac56b41eb59
Revises: 9e2925eec2d2
Create Date: 2026-04-03 18:57:30.112977
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eac56b41eb59'
down_revision: Union[str, None] = '9e2925eec2d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('variables', sa.Column('variable_type', sa.String(length=20), nullable=False, server_default='string'))
    op.drop_column('variables', 'value')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variables', sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('variables', 'variable_type')
    # ### end Alembic commands ###
